"""Canonical warehouse zone catalog (same 7 zones everywhere)."""

CUSTOMS_WAREHOUSE_ZONES = [
    {
        "code": "Z-IN",
        "name": "Receiving Area",
        "purpose": "Inbound goods receipt and initial inspection.",
        "category": "receiving",
        "security_level": "standard",
        "sort_order": 1,
        "description": "Goods receiving and initial inspection zone",
        "vms_zone_type": "Restricted",
        "requires_escort": False,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-DA",
        "name": "Detained Articles",
        "purpose": "Temporary holding of detained articles under investigation.",
        "category": "detained",
        "security_level": "restricted",
        "sort_order": 2,
        "description": "Temporarily held goods under investigation",
        "vms_zone_type": "Restricted",
        "requires_escort": True,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-SZ",
        "name": "Seizure Zone",
        "purpose": "Secure containment of seized or confiscated goods.",
        "category": "seizure",
        "security_level": "high",
        "sort_order": 3,
        "description": "Seized/confiscated goods (high security)",
        "vms_zone_type": "High Security",
        "requires_escort": True,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-EX",
        "name": "Examination Zone",
        "purpose": "Operational inspection and testing of goods.",
        "category": "examination",
        "security_level": "restricted",
        "sort_order": 4,
        "description": "Goods under examination and testing",
        "vms_zone_type": "Restricted",
        "requires_escort": True,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-ST",
        "name": "General Stock",
        "purpose": "General storage for cleared inventory.",
        "category": "stock",
        "security_level": "standard",
        "sort_order": 5,
        "description": "General storage and warehousing",
        "vms_zone_type": "Public",
        "requires_escort": False,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-DI",
        "name": "Disposal Zone",
        "purpose": "Staging area for goods scheduled for disposal.",
        "category": "disposal",
        "security_level": "restricted",
        "sort_order": 6,
        "description": "Goods marked for destruction or disposal",
        "vms_zone_type": "Restricted",
        "requires_escort": True,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
    {
        "code": "Z-RL",
        "name": "Release Zone",
        "purpose": "Final clearance and release staging for collected goods.",
        "category": "release",
        "security_level": "standard",
        "sort_order": 7,
        "description": "Cleared goods ready for collection/release",
        "vms_zone_type": "Restricted",
        "requires_escort": False,
        "access_hours_start": "06:00",
        "access_hours_end": "22:00",
        "weekend_access": False,
        "max_occupancy": 10,
        "allowed_visitor_categories": [],
        "gate_ids": [],
        "camera_ids": [],
    },
]


def get_zone_by_code(code: str) -> dict | None:
    """Get zone definition by code."""
    for zone in CUSTOMS_WAREHOUSE_ZONES:
        if zone["code"] == code:
            return zone
    return None
