# Generated by Django 5.2.11 on 2026-07-21 12:22

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def backfill_attendance_metadata(apps, schema_editor):
    Attendance = apps.get_model("users", "Attendance")
    work_start = datetime.time(9, 0)
    late_after = datetime.time(9, 30)

    for row in Attendance.objects.all().iterator():
        updates = []
        if row.check_in:
            local_t = timezone.localtime(row.check_in).time()
            if local_t <= work_start:
                new_status = "present"
            else:
                new_status = "late"
            if row.status != new_status:
                row.status = new_status
                updates.append("status")
        if not row.source:
            row.source = "manual"
            updates.append("source")
        if updates:
            row.save(update_fields=updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_attendance_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "-check_in"]},
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendance",
            name="source",
            field=models.CharField(
                choices=[
                    ("cctv", "CCTV"),
                    ("manual", "Manual"),
                    ("webcam", "Webcam"),
                    ("camera", "Camera"),
                    ("kiosk", "Kiosk"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("half_day", "Half Day"),
                ],
                default="present",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(backfill_attendance_metadata, noop_reverse),
    ]
