# Generated by Django 5.2.11 on 2026-07-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0011_alter_detectionevent_clip_and_more'),
        ('users', '0021_attendance_insightface_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('confidence', models.FloatField(default=0.0)),
                ('attendance_action', models.CharField(blank=True, max_length=32)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_snapshots', to='cameras.camera')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_snapshots', to='users.staff')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='recognition/profile/')),
                ('dataset_folder', models.CharField(max_length=255, unique=True)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('is_trained', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='InsightFace_v1', max_length=50)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollment', to='users.staff')),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
    ]
