# Generated by Django 5.2.14 on 2026-06-03 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(help_text='e.g., PESHAWAR, DI_KHAN (should match User.location)', max_length=50)),
                ('code', models.CharField(help_text='e.g., WH-DIK-RETTA', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g., New Warehouse, Retta Kulachi', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'ordering': ['location_code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SiteZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., Z-IN, Z-DA (one of the 7 canonical codes)', max_length=20)),
                ('name', models.CharField(help_text='e.g., Receiving Area', max_length=255)),
                ('category', models.CharField(choices=[('receiving', 'Receiving'), ('detained', 'Detained Articles'), ('seizure', 'Seizure'), ('examination', 'Examination'), ('stock', 'General Stock'), ('disposal', 'Disposal'), ('release', 'Release')], default='stock', max_length=50)),
                ('security_level', models.CharField(choices=[('standard', 'Standard'), ('restricted', 'Restricted'), ('high', 'High')], default='standard', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (1-7)')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional SOP text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Site Zone',
                'verbose_name_plural': 'Site Zones',
                'ordering': ['warehouse', 'sort_order'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
    ]
