# Generated by Django 5.2.14 on 2026-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitezone',
            name='access_hours_end',
            field=models.CharField(default='22:00', max_length=5),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='access_hours_start',
            field=models.CharField(default='06:00', max_length=5),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='allowed_visitor_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='camera_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='gate_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='requires_escort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='vms_zone_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Restricted', 'Restricted'), ('High Security', 'High Security'), ('Admin', 'Admin')], default='Public', max_length=50),
        ),
        migrations.AddField(
            model_name='sitezone',
            name='weekend_access',
            field=models.BooleanField(default=False),
        ),
    ]
