# Generated by Django 5.2.14 on 2026-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_sitezone_access_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitezone',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='Visitor/operational purpose of the zone', max_length=255),
        ),
    ]
