# Generated by Django 5.2.11 on 2026-06-10 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camerartspsettings'),
        ('warehouse', '0003_sitezone_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detention_memo_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_row_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('case_ref', models.CharField(blank=True, db_index=True, max_length=200)),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('pct_code', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='PCS', max_length=40)),
                ('godown_warehouse', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, default='In Custody', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detention_memo_id', models.UUIDField(db_index=True)),
                ('detention_case_no', models.CharField(blank=True, max_length=120)),
                ('video', models.FileField(blank=True, null=True, upload_to=warehouse.models.distribution_video_path)),
                ('outcome', models.CharField(blank=True, choices=[('inventory_deducted', 'Inventory deducted'), ('destructed', 'Marked destructed')], default='', max_length=32)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('inventory_deductions', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
