# Generated by Django 5.2.14 on 2026-06-12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0004_alter_camera_frame_rate"),
        ("warehouse", "0004_memo_distribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="memodistribution",
            name="camera_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="memodistribution",
            name="camera_videos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="memodistribution",
            name="location_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="memodistribution",
            name="selected_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="memodistribution",
            name="smoke_fire_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DestructionAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("detention_memo_id", models.UUIDField(db_index=True)),
                ("detention_case_no", models.CharField(blank=True, max_length=120)),
                ("location_code", models.CharField(blank=True, default="", max_length=64)),
                ("alert_type", models.CharField(default="fire_smoke", max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High")],
                        default="critical",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("detection_class", models.CharField(blank=True, max_length=80)),
                ("confidence", models.FloatField(default=0)),
                ("detection_data", models.JSONField(blank=True, default=dict)),
                ("notified_user_ids", models.JSONField(blank=True, default=list)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destruction_alerts",
                        to="cameras.camera",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="warehouse.memodistribution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
