# Generated by Django 5.2.14 on 2026-06-12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0004_alter_camera_frame_rate"),
        ("warehouse", "0005_destruction_enhancements"),
    ]

    operations = [
        migrations.CreateModel(
            name="FireSmokeDetectionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("detention_memo_id", models.UUIDField(db_index=True)),
                ("detention_case_no", models.CharField(blank=True, max_length=120)),
                ("detention_fir_number", models.CharField(blank=True, max_length=120)),
                ("warehouse_name", models.CharField(blank=True, default="", max_length=400)),
                ("location_code", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("place_of_detention", models.CharField(blank=True, default="", max_length=300)),
                ("place_of_occurrence", models.CharField(blank=True, default="", max_length=300)),
                ("camera_code", models.CharField(blank=True, default="", max_length=32)),
                ("camera_name", models.CharField(blank=True, default="", max_length=150)),
                ("camera_ip", models.CharField(blank=True, default="", max_length=45)),
                ("camera_zone", models.CharField(blank=True, default="", max_length=64)),
                ("camera_site_label", models.CharField(blank=True, default="", max_length=150)),
                ("detection_class", models.CharField(blank=True, max_length=80)),
                ("detection_label", models.CharField(blank=True, max_length=120)),
                ("confidence", models.FloatField(default=0)),
                ("bbox", models.JSONField(blank=True, default=list)),
                ("detection_count", models.PositiveIntegerField(default=1)),
                ("detections", models.JSONField(blank=True, default=list)),
                ("alert_triggered", models.BooleanField(default=False)),
                ("notified_user_ids", models.JSONField(blank=True, default=list)),
                ("performed_by", models.CharField(blank=True, max_length=150)),
                ("session_status", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fire_smoke_logs",
                        to="cameras.camera",
                    ),
                ),
                (
                    "destruction_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_logs",
                        to="warehouse.destructionalert",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fire_smoke_logs",
                        to="warehouse.memodistribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fire/Smoke detection log",
                "verbose_name_plural": "Fire/Smoke detection logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
