# Generated by Django 5.2.11 on 2026-06-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Site code e.g. PESHAWAR', max_length=64)),
                ('site_label', models.CharField(blank=True, default='', help_text='Area within site e.g. Main Gate', max_length=150)),
                ('zone', models.CharField(blank=True, default='', max_length=64)),
                ('camera_type', models.CharField(choices=[('PTZ', 'PTZ'), ('Fixed', 'Fixed'), ('Thermal', 'Thermal'), ('360', '360°')], default='Fixed', max_length=16)),
                ('purpose', models.CharField(choices=[('surveillance', 'General Surveillance'), ('object_detection', 'Object Detection (YOLO)'), ('face_recognition', 'Face Recognition'), ('attendance', 'Attendance Check-in'), ('anpr', 'ANPR / Vehicle'), ('zone_monitoring', 'Zone Access Monitoring'), ('thermal', 'Thermal Anomaly')], default='surveillance', max_length=32)),
                ('stream_url', models.TextField(help_text='RTSP, HTTP MP4, or relative path')),
                ('resolution', models.CharField(blank=True, default='1920x1080', max_length=32)),
                ('frame_rate', models.CharField(blank=True, default='30', max_length=8)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=16)),
                ('recording', models.BooleanField(default=True)),
                ('storage_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField(default=list)),
                ('is_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
