# Generated by Django 5.2.11 on 2026-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, default='', help_text='Camera IP — RTSP URL built from .env', max_length=45),
        ),
    ]
