# Generated by Django 5.2.11 on 2026-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRtspSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=64)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('port', models.PositiveIntegerField(default=554)),
                ('path', models.CharField(default='/Streaming/Channels/101', max_length=255)),
                ('ips', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera RTSP settings',
                'verbose_name_plural': 'Camera RTSP settings',
            },
        ),
    ]
