# Generated by Django 5.2.14 on 2026-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camerartspsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='frame_rate',
            field=models.CharField(blank=True, default='25', max_length=8),
        ),
    ]
