# Generated by Django 5.2.11 on 2026-07-11 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detentions', '0002_alter_detentionmemo_options_depositaccountentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.CharField(blank=True, max_length=40)),
                ('examining_officer', models.CharField(blank=True, max_length=200)),
                ('goods_condition', models.CharField(blank=True, max_length=400)),
                ('valuation_notes', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('document_relevance', models.CharField(choices=[('Pending', 'Pending'), ('Relevant', 'Relevant'), ('Not Relevant', 'Not Relevant')], db_index=True, default='Pending', max_length=40)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detention_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=400)),
                ('content', models.TextField(blank=True)),
                ('case_no', models.CharField(blank=True, db_index=True, max_length=120)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=40)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detention_memo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sheet', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Dangerous/Chemical', 'Dangerous/Chemical'), ('Perishable', 'Perishable'), ('Other', 'Other')], default='Other', max_length=40)),
                ('recovery_date', models.CharField(blank=True, max_length=40)),
                ('recovery_officer', models.CharField(blank=True, max_length=200)),
                ('goods_description', models.TextField(blank=True)),
                ('quantity', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=40)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_memos', to='seizure_management.detentionassessment')),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_memos', to='detentions.depositaccountentry')),
                ('detention_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_memos', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeizureReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.CharField(blank=True, max_length=40)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('recovery_assessment_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seizure_reports', to='seizure_management.detentionassessment')),
                ('detention_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seizure_reports', to='detentions.detentionmemo')),
                ('recovery_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seizure_reports', to='seizure_management.recoverymemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
