# Generated by Django 5.2.11 on 2026-07-11 08:27

import django.db.models.deletion
import seizure_management.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='accused_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='accused_cnic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='accused_father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='accused_mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='accused_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='badge_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='date_time',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='evidence_collected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='forward_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='gps_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='grounds_of_suspicion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='inspection_date',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='note_sheet_no',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='ntn_strn',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='officer_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='place_of_inspection',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='preliminary_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='prepared_date',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='prepared_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('No Action', 'No Action'), ('Warning', 'Warning'), ('Further Investigation', 'Further Investigation'), ('Issue Detention Memo', 'Issue Detention Memo'), ('Release Goods', 'Release Goods')], default='Issue Detention Memo', max_length=60),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='warehouse_shop',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=40),
        ),
        migrations.CreateModel(
            name='NoteSheetAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=seizure_management.models.note_sheet_attachment_path)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('pdf', 'PDF'), ('invoice', 'Invoice'), ('delivery_challan', 'Delivery Challan'), ('import_document', 'Import Document'), ('cnic', 'CNIC'), ('other', 'Other')], default='other', max_length=40)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='seizure_management.notesheet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSheetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=300)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('estimated_value', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=400)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seizure_management.notesheet')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
