# Generated by Django 5.2.11 on 2026-07-11 08:38

import django.db.models.deletion
import seizure_management.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0002_notesheet_accused_address_notesheet_accused_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheetitem',
            name='client_line_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheetitem',
            name='condition',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notesheetitem',
            name='identification_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesheetitem',
            name='pct_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notesheetitem',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notesheetitem',
            name='qr_code_number',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='NoteSheetItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=seizure_management.models.note_sheet_item_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seizure_management.notesheetitem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
