# Generated by Django 5.2.11 on 2026-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0003_notesheetitem_goods_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='accused_father_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='accused_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='approved_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='business_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='department',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='forward_to',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='office',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='officer_contact',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='place_of_inspection',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='prepared_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='warehouse_shop',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notesheetitem',
            name='identification_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
