# Generated by Django 5.2.11 on 2026-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0004_notesheet_widen_char_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='forward_to_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
