# Generated by Django 5.2.11 on 2026-07-11 09:53

import seizure_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0005_notesheet_forward_to_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheetattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=seizure_management.models.note_sheet_attachment_path),
        ),
        migrations.AlterField(
            model_name='notesheetitemimage',
            name='image',
            field=models.FileField(max_length=500, upload_to=seizure_management.models.note_sheet_item_image_path),
        ),
    ]
