# Generated by Django 5.2.11 on 2026-07-11 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0008_drop_legacy_assessment_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSheetNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seizure_management.notesheet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user_id', 'is_read', '-created_at'], name='seizure_man_recipie_81d793_idx')],
            },
        ),
    ]
