# Generated by Django 5.2.11 on 2026-07-11 12:08

import django.db.models.deletion
import seizure_management.models
import uuid
from django.db import migrations, models


def map_legacy_assessment_status(apps, schema_editor):
    DetentionAssessment = apps.get_model("seizure_management", "DetentionAssessment")
    DetentionAssessment.objects.filter(status="In Progress").update(status="Draft")
    DetentionAssessment.objects.filter(status="Completed").update(status="Approved")


def unmap_legacy_assessment_status(apps, schema_editor):
    DetentionAssessment = apps.get_model("seizure_management", "DetentionAssessment")
    DetentionAssessment.objects.filter(status="Draft").update(status="In Progress")
    DetentionAssessment.objects.filter(status="Approved").update(status="Completed")


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0009_notesheet_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentionassessment',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='approved_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='detentionassessment',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(map_legacy_assessment_status, unmap_legacy_assessment_status),
        migrations.AlterField(
            model_name='detentionassessment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=40),
        ),
        migrations.CreateModel(
            name='DetentionAssessmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=seizure_management.models.assessment_attachment_path)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('pdf', 'PDF'), ('invoice', 'Invoice'), ('delivery_challan', 'Delivery Challan'), ('import_document', 'Import Document'), ('cnic', 'CNIC'), ('other', 'Other')], default='other', max_length=40)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='seizure_management.detentionassessment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seizure_management.detentionassessment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user_id', 'is_read', '-created_at'], name='seizure_man_recipie_12708d_idx')],
            },
        ),
    ]
