# Generated by Django 5.2.11 on 2026-07-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0014_align_seizure_report_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recoverynotification',
            new_name='seizure_man_recipie_62ee39_idx',
            old_name='seizure_man_recipie_recov_idx',
        ),
    ]
