# Generated by Django 5.2.14 on 2026-06-12 12:08

import detentions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0001_memo_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detentionmemo',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DepositAccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treasury_challan_no', models.CharField(blank=True, max_length=120)),
                ('deposit_type', models.CharField(blank=True, max_length=80)),
                ('case_seizure_ref', models.CharField(blank=True, max_length=200)),
                ('fir_no', models.CharField(blank=True, max_length=120)),
                ('customs_station', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=120)),
                ('deposit_date', models.CharField(blank=True, max_length=40)),
                ('bank_treasury_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detention_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_entries', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetentionMemoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to=detentions.models.detention_attachment_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetentionMemoGoodsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_line_id', models.CharField(blank=True, max_length=80)),
                ('qr_code_number', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('pct_code', models.CharField(blank=True, max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('condition', models.CharField(blank=True, max_length=80)),
                ('assessable_value_pkr', models.CharField(blank=True, max_length=40)),
                ('identification_ref', models.CharField(blank=True, max_length=200)),
                ('item_notes', models.TextField(blank=True)),
                ('perishable', models.BooleanField(default=False)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_lines', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetentionMemoGoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=detentions.models.detention_goods_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goods_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='detentions.detentionmemogoodsline')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
