# Generated by Django 5.2.11 on 2026-02-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_add_host_email_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='expiry_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('expired', 'expired'), ('revoked', 'revoked')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
